services:
  db:
    image: mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3307:3306'

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - '8080:8080'
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_PORT: 3306
      DB_HOST: db
      RAILS_MAX_THREADS: 5
      RAILS_ENV: development

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - '3003:3003'
volumes:
  bundle:
