services:
  db:
    image: mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3307:3306'
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql

  backend:
    build:
      context: ./backend
    volumes:
      - type: bind
        source: ./backend
        target: /usr/src/app
      - type: volume
        source: bundle
        target: /usr/local/bundle
    ports:
      - '8080:8080'
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_PORT: 3306
      DB_HOST: db
      RAILS_MAX_THREADS: 5
      RAILS_ENV: development

  frontend:
    build:
      context: ./frontend
    volumes:
      - type: bind
        source: ./frontend
        target: /usr/src/app
      - type: bind
        source: ./frontend/node_modules
        target: /usr/src/app/node_modules
    ports:
      - '3003:3003'
volumes:
  mysql_data:
  bundle:
  node_modules:
