require: 
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-rspec_rails


AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "config/**/*"
    - "bin/*"
    - "node_modules/**/*"
    - "lib/**/*"

  NewCops: enable

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false