# fly.toml app configuration file generated for mysql-fly-kiwi-power on 2024-08-14T21:01:17+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mysql-fly-kiwi-power'
primary_region = 'nrt'

[build]
  image = 'mysql:8.0'

[env]
  MYSQL_DATABASE = 'some_db'
  MYSQL_USER = 'non_root_user'

[processes]
  app = '--datadir /data/mysql --default-authentication-plugin mysql_native_password'

[[mounts]]
  source = 'mysqldata'
  destination = '/data'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
