# fly.toml app configuration file generated for mysql-fly-misty-moon-2068 on 2024-08-12T19:11:01+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mysql-fly-misty-moon-2068'
primary_region = 'nrt'

[build]
  image = 'mysql:8.0'

#[http_service]
#  internal_port = 3306
#  force_https = true
#  auto_stop_machines = 'stop'
#  auto_start_machines = true
#  min_machines_running = 0
#  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  MYSQL_DATABASE = "some_db"
  MYSQL_USER = "non_root_user"

[processes]
  app = """--datadir /data/mysql_ \
    --default-authentication-plugin mysql_native_password"""
[mounts]
  source = "mysqldata"
  destination = "/data"
